function GameData (props){
    //c, L, I, 3, 4 
    const initialPipes = [
        { id: 1, type: "L" , pos:"0"},{ id: 2, type: "3" , pos:"90"},{ id: 3, type: "L" , pos:"180"},{ id: 4, type: "c" , pos:"270"},{ id: 5, type: "c" , pos:"0"},{ id: 6, type: "c" , pos:"0"},{ id: 7, type: "L" , pos:"0"},
        { id: 8, type: "c" , pos:"0"},
        { id: 9, type: "c" , pos:"0"},
        { id: 10, type: "c" , pos:"0"},
        { id: 11, type: "3" , pos:"0"},
        { id: 12, type: "L" , pos:"0"},
        { id: 13, type: "I" , pos:"0"},
        { id: 14, type: "I" , pos:"0"},
        { id: 15, type: "L" , pos:"0"},
        { id: 16, type: "L" , pos:"0"},
        { id: 17, type: "c" , pos:"0"},
        { id: 18, type: "L" , pos:"90"},
        { id: 19, type: "I" , pos:"180"},
        { id: 20, type: "c" , pos:"270"},
        { id: 21, type: "4" , pos:"0"},
        { id: 22, type: "4" , pos:"0"},
        { id: 23, type: "c" , pos:"0"},
        { id: 24, type: "I" , pos:"0"},
        { id: 25, type: "c" , pos:"0"},
        { id: 26, type: "4" , pos:"0"},
        { id: 27, type: "4" , pos:"0"},
        { id: 28, type: "L" , pos:"0"},
        { id: 29, type: "c" , pos:"0"},
        { id: 30, type: "L" , pos:"0"},
        { id: 31, type: "3" , pos:"0"},
        { id: 32, type: "L" , pos:"0"},
        { id: 33, type: "c" , pos:"90"},
        { id: 34, type: "I" , pos:"180"},
        { id: 35, type: "I" , pos:"270"},
        { id: 36, type: "L" , pos:"0"},
        { id: 37, type: "L" , pos:"0"},
        { id: 38, type: "L" , pos:"0"},
        { id: 39, type: "3" , pos:"0"},
        { id: 40, type: "L" , pos:"0"},
        { id: 41, type: "I" , pos:"0"},
        { id: 42, type: "I" , pos:"0"},
        { id: 43, type: "I" , pos:"0"},
        { id: 44, type: "c" , pos:"0"},
        { id: 45, type: "4" , pos:"0"},
        { id: 46, type: "3" , pos:"0"},
        { id: 47, type: "c" , pos:"0"},
        { id: 48, type: "c" , pos:"0"},
        { id: 49, type: "3" , pos:"0"},
        { id: 50, type: "L" , pos:"0"},
        { id: 51, type: "I" , pos:"0"},
        { id: 52, type: "c" , pos:"0"},
        { id: 53, type: "c" , pos:"0"},
        { id: 54, type: "I" , pos:"0"},
        { id: 55, type: "3" , pos:"0"},
        { id: 56, type: "c" , pos:"0"},
        { id: 57, type: "c" , pos:"0"},
        { id: 58, type: "c" , pos:"0"},
        { id: 59, type: "3" , pos:"0"},
        { id: 60, type: "3" , pos:"0"},
        { id: 61, type: "c" , pos:"0"},
        { id: 62, type: "L" , pos:"0"},
        { id: 63, type: "3" , pos:"0"},
        { id: 64, type: "c" , pos:"0"}
      ];
    
    return initialPipes
}



  export default GameData 